language: go

# Enable docker & docker-compose.
services:
  - docker

# Set compiler version to 1.13 latest.
go:
  - 1.13.x

install: true

script:
  - cp .env.dist .env
  - docker-compose up -d
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)